### ISSUE TITLE
supavisor install missing info & fails when applying migrations

### ISSUE THREAD

**Issue by srasul** [supabase/supavisor#168]
# Bug report

## Describe the bug

Two issues:

1. in the install docs, we are missing command to get the dependencies. The following command is needed after cloning the repo:

`mix deps.get`

2. Cannot get supavisor working locally. When applying the migrations via `mix ecto.migrate --prefix _supavisor --log-migrator-sql`, I get the following error:

```
$ mix ecto.migrate --prefix _supavisor --log-migrator-sql
==> opentelemetry_semantic_conventions
Compiling 1 file (.erl)
Compiling 3 files (.ex)
Generated opentelemetry_semantic_conventions app
==> typed_struct
Compiling 2 files (.ex)
Generated typed_struct app
==> file_system
Compiling 7 files (.ex)
Generated file_system app
==> connection
Compiling 1 file (.ex)
Generated connection app
==> deep_merge
Compiling 2 files (.ex)
Generated deep_merge app
===> Analyzing applications...
===> Compiling poolboy
==> eternal
Compiling 5 files (.ex)
Generated eternal app
==> decimal
Compiling 4 files (.ex)
Generated decimal app
==> mime
Compiling 1 file (.ex)
Generated mime app
==> artificery
Compiling 10 files (.ex)
Generated artificery app
==> distillery
Compiling 33 files (.ex)

== Compilation error in file lib/distillery/releases/runtime/control.ex ==
** (RuntimeError) error parsing file /usr/lib/erlang/lib/runtime_tools-2.0/include/observer_backend.hrl, got: {:error, :enoent}
    (elixir 1.15.6) lib/record/extractor.ex:84: Record.Extractor.read_file/2
    (elixir 1.15.6) lib/record/extractor.ex:50: Record.Extractor.extract_record/2
    lib/distillery/releases/runtime/control.ex:10: (module)
could not compile dependency :distillery, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile distillery --force", update it with "mix deps.update distillery" or clean it with "mix deps.clean distillery"
```

## To Reproduce
1. clone git repo
2. run postgres via docker: `docker compose -f postgresql.yml up`
3. run `mix deps.get`
4. run `mix ecto.migrate --prefix _supavisor --log-migrator-sql` 

## System information
OS: Ubuntu 22.04.3 LTS
mix version:
```
$ mix --version
Erlang/OTP 26 [erts-14.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Mix 1.15.6 (compiled with Erlang/OTP 26)
```

## Additional context
I tried this on the `main` branch and also on the `v0.9.0` tag. Both had the same problem described above.

**Comment by abc3** [comment]
Thank you for your bug report!

**Comment by abc3** [comment]
The [fix](https://github.com/supabase/supavisor/pull/170) has already been merged to main, try it again, please
